### ISSUE TITLE
[solver] Belos based solver crashes with Trilinos Debug built

### ISSUE THREAD

**Issue by vovannikov** [4C-multiphysics/4C#1596]
## Bug Description: What's going wrong?
It seems all tests which use `Belos` crash in 4C compiled with the recommended version of Trilinos (most probably with all others too) when Trilinos is build in `Debug`. This
```
~/4C-debug/4C ~/4C/tests/input_files/elch_gaussian_hill_pbc_NP_genalpha_calcInitDt_calcInitPot.4C.yaml test1
```
produces this crash:
```
Setup of KrylovSpaceProjection in scatra field


Setup of splitter: numscal = 2
Constant F/R = 11604.5
SCATRA: calculating initial field for electric potential

TIME:  0.0000E+00/ 1.0000E+00  DT =  1.0000E-02    Gen. Alpha  (a_F=0.67 | a_M=0.83 | gamma=0.67) STEP =    0/   2
+------------+-------------------+--------------+--------------+
|- step/max -|- tol      [norm] -|-- pot-res ---|-- pot-inc ---|
|    1/  2   |  1.000e-09[L_2 ]  |  3.710e-09   |      --      | (      --     ,te= 1.447e+00)
*******************************************************
Recomputation due to reaching 0 nonlinear steps.
Recomputation due to reset.
Compute preconditioner
*** Process received signal ***
Signal: Segmentation fault (11)
Signal code: Invalid permissions (2)
Failing at address: 0x7ff83d04bb2c
[ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x45330)[0x7f61d5ab5330]
[ 1] /4C-debug/4C(_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE4sizeEv+0x10)[0x7f61fd031c06]
[ 2] /4C-debug/4C(_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7compareERKS4_+0x40)[0x7f61fd05aeb2]
[ 3] /4C-debug/4C(_ZStssIcSt11char_traitsIcESaIcEEDTcl21__char_traits_cmp_catIT0_ELi0EEERKNSt7__cxx1112basic_stringIT_S3_T1_EESB_+0x27)[0x7f61fd058527]
[ 4] /4C-debug/4C(_ZNKSt4lessINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEclERKS5_S8_+0x2b)[0x7f61fd056a7b]
[ 5] /4C-debug/4C(_ZNKSt8_Rb_treeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS5_N7Teuchos44StringIndexedOrderedValueObjectContainerBase12OrdinalIndexEESt10_Select1stISB_ESt4lessIS5_ESaISB_EE14_M_lower_boundEPKSt13_Rb_tree_nodeISB_EPKSt18_Rb_tree_node_baseRS7_+0x53)[0x7f61fd0587f3]
[ 6] /4C-debug/4C(_ZNKSt8_Rb_treeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS5_N7Teuchos44StringIndexedOrderedValueObjectContainerBase12OrdinalIndexEESt10_Select1stISB_ESt4lessIS5_ESaISB_EE4findERS7_+0x58)[0x7f61fd056bbc]
[ 7] /4C-debug/4C(_ZNKSt3mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEN7Teuchos44StringIndexedOrderedValueObjectContainerBase12OrdinalIndexESt4lessIS5_ESaISt4pairIKS5_S8_EEE4findERSC_+0x27)[0x7f61fd054231]
[ 8] /4C-debug/4C(_ZNK7Teuchos40StringIndexedOrderedValueObjectContainerINS_14ParameterEntryEE18getObjOrdinalIndexERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x3a)[0x7f61fd0527be]
[ 9] /4C-debug/4C(_ZNK7Teuchos13ParameterList11getEntryPtrERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x3b)[0x7f61fd0518ad]
[10] /tpl/trilinos-4c-last-debug/lib/libteuchosparameterlist.so.16(_ZNK7Teuchos13ParameterList18validateParametersERKS0_iNS_13EValidateUsedENS_17EValidateDefaultsE+0x20a)[0x7f61d6dbafc0]
[11] /tpl/trilinos-4c-last-debug/lib/libstratimikos.so.16(_ZN11Stratimikos19LinearSolverBuilderIdED1Ev+0xa9)[0x7f61cd893dd3]
[12] /4C-debug/lib4C.so(_ZN5FourC4Core12LinearSolver20IFPACKPreconditioner5setupERNS0_6LinAlg14SparseOperatorERNS3_11MultiVectorIdEE+0x9c8)[0x7f61f231b132]
[13] /4C-debug/lib4C.so(_ZN5FourC4Core12LinearSolver24ProjectionPreconditioner5setupERNS0_6LinAlg14SparseOperatorERNS3_11MultiVectorIdEE+0x16a)[0x7f61f23f4fb6]
[14] /4C-debug/lib4C.so(_ZN5FourC4Core12LinearSolver15IterativeSolver5setupESt10shared_ptrINS0_6LinAlg14SparseOperatorEES3_INS4_11MultiVectorIdEEEbbS3_INS4_21LinearSystemProjectorEE+0x3f2)[0x7f61f21e525a]
[15] /4C-debug/lib4C.so(_ZN5FourC4Core6LinAlg6Solver5setupESt10shared_ptrINS1_14SparseOperatorEES3_INS1_11MultiVectorIdEEES8_RKNS1_12SolverParamsE+0x595)[0x7f61f23018d9]
[16] /4C-debug/lib4C.so(_ZN5FourC4Core6LinAlg6Solver5solveESt10shared_ptrINS1_14SparseOperatorEES3_INS1_6VectorIdEEES8_RKNS1_12SolverParamsE+0xe3)[0x7f61f2301ee7]
[17] /4C-debug/lib4C.so(_ZNK5FourC6ScaTra20MeshtyingStrategyStd5solveERKSt10shared_ptrINS_4Core6LinAlg6SolverEERKS2_INS4_14SparseOperatorEERKS2_INS4_6VectorIdEEESH_SH_iRNS4_12SolverParamsE+0xc6)[0x7f61f834bd98]
[18] /4C-debug/lib4C.so(_ZN5FourC6ScaTra16ScaTraTimIntElch28calc_initial_potential_fieldEv+0x1947)[0x7f61f81a01e3]
[19] /4C-debug/lib4C.so(_ZN5FourC6ScaTra16ScaTraTimIntElch17prepare_time_loopEv+0x12c)[0x7f61f8192fec]
[20] /4C-debug/lib4C.so(_ZN5FourC6ScaTra16ScaTraTimIntImpl9time_loopEv+0x1b5)[0x7f61f823ba19]
[21] /4C-debug/lib4C.so(_ZN5FourC8elch_dynEi+0x7e7)[0x7f61f2f4d5f6]
[22] /4C-debug/4C(_Z17entrypoint_switchv+0x151)[0x7f61fd02d89a]
[23] /4C-debug/4C(_Z3runRN5FourC20CommandlineArgumentsE+0x218)[0x7f61fd085bca]
[24] /4C-debug/4C(main+0xa92)[0x7f61fd0853d7]
[25] /lib/x86_64-linux-gnu/libc.so.6(+0x2a1ca)[0x7f61d5a9a1ca]
[26] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x8b)[0x7f61d5a9a28b]
[27] /4C-debug/4C(_start+0x25)[0x7f61fd02d685]
*** End of error message ***
Segmentation fault (core dumped)
```

Interestingly, this issue does not appear at least in 3a9727aecd (the last prior to delete `--to-yaml` option).

The issue does not reveal itself if 4C (no matter if compiled in release or debug) is linked against release built of Trilinos.

## Steps to Reproduce
1. Compile Trilinos in debug
2. Compile 4C in debug or release
3. Run `elch_gaussian_hill_pbc_NP_genalpha_calcInitDt_calcInitPot.4C.yaml`

## Interested Parties
@maxfirmbach @mayrmt

**Comment by vovannikov** [comment]
In fact, there could be even more bugs in this setting (4C + debug Trilinos). For instance, `f3_drt_genalpha_initialfield_volforce_pbc.4C.yaml` (runs in the minimal test setting) crashes with
```
Setup of KrylovSpaceProjection in fluid field

Stabilization type         : residual_based
                             Evaluation Tau  = element_center
                             Evaluation Mat  = element_center

                             1

                             Tau Type        = Franca_Barrenechea_Valentin_Frey_Wall
                             SUPG            = true
                             PSPG            = true
                             GRAD_DIV        = true
                             CROSS-STRESS    = cross_rhs
                             REYNOLDS-STRESS = reynolds_rhs
                             VSTAB           = usfem_viscous
                             RSTAB           = no_reactive
                             TRANSIENT       = no_transient


TIME:  1.0000E-01/ 1.0000E+03  DT =  1.0000E-01  Np-Generalized-Alpha (gamma = 0.67, alphaF = 0.67, alphaM = 0.83) STEP =    1/   5
+------------+-------------+-------------+-------------+-------------+
|- step/max -|-- vel-res --|-- pre-res --|-- vel-inc --|-- pre-inc --|
|-   norm   -|-- abs. L2 --|-- abs. L2 --|-- rel. L2 --|-- rel. L2 --|
|-   tol    -|  1.000E-09  |  1.000E-09  |  1.000E-09  |  1.000E-09  |
*******************************************************
Recomputation due to reaching 0 nonlinear steps.
Recomputation due to reset.
Compute preconditioner
*******************************************************
terminate called after throwing an instance of 'std::runtime_error'
  what():  /Trilinos/packages/xpetra/src/MultiVector/Xpetra_EpetraMultiVector.hpp:309:

Throw number = 1

Throw test that evaluated to true: (Teuchos::as<size_t>(ArrayOfPtrs[j].size()) != localLength)

Xpetra::EpetraMultiVectorT<int, Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::MultiVector(ArrayOfPtrs): ArrayOfPtrs[0].size() (== 125) is not equal to getLocalLength() (== 80
*** Process received signal ***
Signal: Aborted (6)
Signal code:  (-6)
[ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x45330)[0x7fdead1f5330]
[ 1] /lib/x86_64-linux-gnu/libc.so.6(pthread_kill+0x11c)[0x7fdead24eb2c]
[ 2] /lib/x86_64-linux-gnu/libc.so.6(gsignal+0x1e)[0x7fdead1f527e]
[ 3] /lib/x86_64-linux-gnu/libc.so.6(abort+0xdf)[0x7fdead1d88ff]
[ 4] /lib/x86_64-linux-gnu/libstdc++.so.6(+0xa5ff5)[0x7fdead4b5ff5]
[ 5] /lib/x86_64-linux-gnu/libstdc++.so.6(+0xbb0da)[0x7fdead4cb0da]
[ 6] /lib/x86_64-linux-gnu/libstdc++.so.6(_ZSt10unexpectedv+0x0)[0x7fdead4b5a55]
[ 7] /lib/x86_64-linux-gnu/libstdc++.so.6(+0xbb391)[0x7fdead4cb391]
[ 8] /tpl/trilinos-4c-last-debug/lib/libxpetra.so.16(_ZN6Xpetra18EpetraMultiVectorTIiN6Tpetra12KokkosCompat23KokkosDeviceWrapperNodeIN6Kokkos6SerialENS4_9HostSpaceEEEEC1ERKN7Teuchos3RCPIKNS_3MapIiiS7_EEEERKNS9_9ArrayViewIKNSH_IKdEEEEm+0x66a)[0x7fdea3309f7c]
[ 9] /tpl/trilinos-4c-last-debug/lib/libxpetra.so.16(_ZN6Xpetra18MultiVectorFactoryIdiiN6Tpetra12KokkosCompat23KokkosDeviceWrapperNodeIN6Kokkos6SerialENS4_9HostSpaceEEEE5BuildERKN7Teuchos3RCPIKNS_3MapIiiS7_EEEERKNS9_9ArrayViewIKNSH_IKdEEEEm+0x145)[0x7fdea3303e6d]
[10] /tpl/trilinos-4c-last-debug/lib/libmuelu.so.16(_ZN5MueLu9HierarchyIdiiN6Tpetra12KokkosCompat23KokkosDeviceWrapperNodeIN6Kokkos6SerialENS4_9HostSpaceEEEE20ReplaceCoordinateMapERNS_5LevelE+0x117e)[0x7fdeaab4660e]
[11] /tpl/trilinos-4c-last-debug/lib/libmuelu.so.16(_ZN5MueLu9HierarchyIdiiN6Tpetra12KokkosCompat23KokkosDeviceWrapperNodeIN6Kokkos6SerialENS4_9HostSpaceEEEE5SetupEiN7Teuchos3RCPIKNS_18FactoryManagerBaseEEESD_SD_+0xcb4)[0x7fdeaab37a7c]
[12] /tpl/trilinos-4c-last-debug/lib/libmuelu.so.16(_ZNK5MueLu16HierarchyManagerIdiiN6Tpetra12KokkosCompat23KokkosDeviceWrapperNodeIN6Kokkos6SerialENS4_9HostSpaceEEEE14SetupHierarchyERNS_9HierarchyIdiiS7_EE+0x158d)[0x7fdeaab69ab7]
[13] /tpl/trilinos-4c-last-debug/lib/libmuelu.so.16(_ZNK5MueLu24ParameterListInterpreterIdiiN6Tpetra12KokkosCompat23KokkosDeviceWrapperNodeIN6Kokkos6SerialENS4_9HostSpaceEEEE14SetupHierarchyERNS_9HierarchyIdiiS7_EE+0x8d)[0x7fdeab0ef5d7]
[14] /4C-debug/lib4C.so(_ZN5MueLu26CreateXpetraPreconditionerIdiiN6Tpetra12KokkosCompat23KokkosDeviceWrapperNodeIN6Kokkos6SerialENS4_9HostSpaceEEEEEN7Teuchos3RCPINS_9HierarchyIT_T0_T1_T2_EEEENS9_IN6Xpetra6MatrixISB_SC_SD_SE_EEEERKNS8_13ParameterListE+0xca2)[0x7fdec9b04a79]
[15] /4C-debug/lib4C.so(_ZNK5Thyra26MueLuPreconditionerFactoryIdiiN6Tpetra12KokkosCompat23KokkosDeviceWrapperNodeIN6Kokkos6SerialENS4_9HostSpaceEEEE14initializePrecERKN7Teuchos3RCPIKNS_18LinearOpSourceBaseIdEEEEPNS_18PreconditionerBaseIdEENS_16ESupportSolveUseE+0x2eee)[0x7fdec9afe032]
[16] /4C-debug/lib4C.so(_ZN5Thyra4precIdEEN7Teuchos3RCPINS_18PreconditionerBaseIT_EEEERKNS_25PreconditionerFactoryBaseIS4_EERKNS2_IKNS_12LinearOpBaseIS4_EEEENS_16ESupportSolveUseE+0xa3)[0x7fdec9a50a6c]
[17] /4C-debug/lib4C.so(_ZN5FourC4Core12LinearSolver19MueLuPreconditioner5setupERNS0_6LinAlg14SparseOperatorERNS3_11MultiVectorIdEE+0x1088)[0x7fdec9a5527a]
[18] /4C-debug/lib4C.so(_ZN5FourC4Core12LinearSolver24ProjectionPreconditioner5setupERNS0_6LinAlg14SparseOperatorERNS3_11MultiVectorIdEE+0x16a)[0x7fdec9b24fb6]
[19] /4C-debug/lib4C.so(_ZN5FourC4Core12LinearSolver15IterativeSolver5setupESt10shared_ptrINS0_6LinAlg14SparseOperatorEES3_INS4_11MultiVectorIdEEEbbS3_INS4_21LinearSystemProjectorEE+0x3f2)[0x7fdec991525a]
[20] /4C-debug/lib4C.so(_ZN5FourC4Core6LinAlg6Solver5setupESt10shared_ptrINS1_14SparseOperatorEES3_INS1_11MultiVectorIdEEES8_RKNS1_12SolverParamsE+0x595)[0x7fdec9a318d9]
[21] /4C-debug/lib4C.so(_ZN5FourC4Core6LinAlg6Solver5solveESt10shared_ptrINS1_14SparseOperatorEES3_INS1_6VectorIdEEES8_RKNS1_12SolverParamsE+0xe3)[0x7fdec9a31ee7]
[22] /4C-debug/lib4C.so(_ZN5FourC3FLD20FluidImplicitTimeInt5solveEv+0xb7d)[0x7fdeca8a2bbf]
[23] /4C-debug/lib4C.so(_ZN5FourC3FLD20FluidImplicitTimeInt9time_loopEv+0x243)[0x7fdeca8a116f]
[24] /4C-debug/lib4C.so(_ZN5FourC3FLD20FluidImplicitTimeInt9integrateEv+0x42)[0x7fdeca8a0f28]
[25] /4C-debug/lib4C.so(_ZN5FourC13dyn_fluid_drtEi+0x510)[0x7fdeca80cf92]
[26] /4C-debug/4C(_Z17entrypoint_switchv+0x87)[0x7fded476a7d0]
[27] /4C-debug/4C(_Z3runRN5FourC20CommandlineArgumentsE+0x218)[0x7fded47c2bca]
[28] /4C-debug/4C(main+0xa92)[0x7fded47c23d7]
[29] /lib/x86_64-linux-gnu/libc.so.6(+0x2a1ca)[0x7fdead1da1ca]
*** End of error message ***
Aborted (core dumped)
```

**Comment by amgebauer** [comment]
Reminds me of #63, which we should definitely tackle (especially since the problem in the brownian dynamic tests have been fixed in the meantime.

**Comment by amgebauer** [comment]
Note, with #1597, the test still fails, but with a different error:

```
+--------------------------------------------------------------------+
| fill_complete() on discretization scatra                           |
| assign_degrees_of_freedom() ...                                    |
| initialize_elements() ...                                          |
| boundary_conditions_geometry() ...                                 |
+--------------------------------------------------------------------+
PARMETIS ERROR: sum weight for constraint 0 is zero.
terminate called after throwing an instance of 'std::runtime_error'
  what():  
ParMETIS returned an error; no valid partition generated.
Look for 'PARMETIS ERROR' in your output for more details.

[helmholtz:2444480] *** Process received signal ***
[helmholtz:2444480] Signal: Aborted (6)
[helmholtz:2444480] Signal code:  (-6)
[helmholtz:2444480] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x45330)[0x7e219ce45330]
[helmholtz:2444480] [ 1] /lib/x86_64-linux-gnu/libc.so.6(pthread_kill+0x11c)[0x7e219ce9eb2c]
[helmholtz:2444480] [ 2] /lib/x86_64-linux-gnu/libc.so.6(gsignal+0x1e)[0x7e219ce4527e]
[helmholtz:2444480] [ 3] /lib/x86_64-linux-gnu/libc.so.6(abort+0xdf)[0x7e219ce288ff]
[helmholtz:2444480] [ 4] /lib/x86_64-linux-gnu/libstdc++.so.6(+0xa5ff5)[0x7e219d2a5ff5]
[helmholtz:2444480] [ 5] /lib/x86_64-linux-gnu/libstdc++.so.6(+0xbb0da)[0x7e219d2bb0da]
[helmholtz:2444480] [ 6] /lib/x86_64-linux-gnu/libstdc++.so.6(_ZSt10unexpectedv+0x0)[0x7e219d2a5a55]
[helmholtz:2444480] [ 7] /lib/x86_64-linux-gnu/libstdc++.so.6(+0xbb391)[0x7e219d2bb391]
[helmholtz:2444480] [ 8] /home/gebauer/work/4C/4C/build/debug/lib4C.so(_ZN7Zoltan219PartitioningProblemINS_21XpetraCrsGraphAdapterI15Epetra_CrsGraph18Epetra_MultiVectorEEE5solveEb+0x7b8)[0x7e21cd320cd8]
[helmholtz:2444480] [ 9] /home/gebauer/work/4C/4C/build/debug/lib4C.so(_ZN5FourC4Core9Rebalance15rebalance_graphERKNS0_6LinAlg5GraphERN7Teuchos13ParameterListERKSt10shared_ptrINS2_6VectorIdEEERKS9_INS2_12SparseMatrixEERKS9_INS2_11MultiVectorIdEEE+0x7ea)[0x7e21cd317cba]
[helmholtz:2444480] [10] /home/gebauer/work/4C/4C/build/debug/lib4C.so(_ZN5FourC4Core10Conditions26PeriodicBoundaryConditions12balance_loadEv+0x1771)[0x7e21cc6b72b1]
[helmholtz:2444480] [11] /home/gebauer/work/4C/4C/build/debug/lib4C.so(_ZN5FourC4Core10Conditions26PeriodicBoundaryConditions44update_dofs_for_periodic_boundary_conditionsEv+0xdf)[0x7e21cc6b2c6f]
[helmholtz:2444480] [12] /home/gebauer/work/4C/4C/build/debug/lib4C.so(_ZN5FourC6ScaTra16ScaTraTimIntImpl4initEv+0x1cb)[0x7e21d27b942b]
[helmholtz:2444480] [13] /home/gebauer/work/4C/4C/build/debug/lib4C.so(_ZN5FourC6ScaTra24ScaTraTimIntElchGenAlpha4initEv+0x2e)[0x7e21d277b8fe]
[helmholtz:2444480] [14] /home/gebauer/work/4C/4C/build/debug/lib4C.so(_ZN5FourC7Adapter19ScaTraBaseAlgorithm4initEv+0x31)[0x7e21cab12641]
[helmholtz:2444480] [15] /home/gebauer/work/4C/4C/build/debug/lib4C.so(_ZN5FourC8elch_dynEi+0x9db)[0x7e21cdc6ef5b]
[helmholtz:2444480] [16] ./4C(_Z17entrypoint_switchv+0x121)[0x5690c48d1a11]
[helmholtz:2444480] [17] ./4C(_Z3runRN5FourC20CommandlineArgumentsE+0x2ac)[0x5690c49284ec]
[helmholtz:2444480] [18] ./4C(main+0x10bd)[0x5690c4927aed]
[helmholtz:2444480] [19] /lib/x86_64-linux-gnu/libc.so.6(+0x2a1ca)[0x7e219ce2a1ca]
[helmholtz:2444480] [20] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x8b)[0x7e219ce2a28b]
[helmholtz:2444480] [21] ./4C(_start+0x25)[0x5690c48d1825]
[helmholtz:2444480] *** End of error message ***
Aborted (core dumped)
```

**Comment by ischeider** [comment]
Even this issue is closed, the error persists for specific build scenarios.
Namely, it happened to me that I also got a ParMETIS Error during the execution of some examples of the test suite on our cluster.
The reason was that my suitesparse installation, which comes with its own metis library, was inconsistent with my self-built parmetis library (from https://karypis.github.io/glaros/software/metis/overview.html). 

At the end of the day, I was only able to solve the problem by adding 
```
  MY_METIS_LIB="-L/my/path/to/parmetis/lib -lmetis" \ 

  MY_METIS_INC="/my/path/to/parmetis/include" 
```
to the make command of suitesparse, and also adding `/my/path/to/parmetis/lib` to `LD_LIBRARY_PATH`. With these modifications, my installed libmetis.so was the only one used by all third-party libraries.
I guess this is likely to happen when metis and/or parmetis is not used from a system-wide installation.

Since it took me more than a day to figure that out, it might be worth mentioning. Maybe we can even post some of those hacks in the documentation, what do others think?

**Comment by amgebauer** [comment]
What about adding subsection "troobleshooting" to the "installation" section in our docu, where we can document such common errors that are related to the installation process?
